### ISSUE TITLE
View name inconsistency

### ISSUE THREAD

**Issue by notxcain** [ReactiveCouchbase/ReactiveCouchbase-play#37]
When using Evolutions plugin in dev mode it prepends name with `dev_`, however when using `search` it does not. Is there any way to create production view while running in dev mode?

**Comment by mathieuancelin** [comment]
Yes, as the evolution plugin is supposed to have different behavior based on the current environment to help you during development,  it tries to be smart about design doc names and impose the `dev_` convention.

If you want to use the same convention with other APIs, you can use

```scala
bucket.docName("myAwesomeDoc")
```

and the behavior will be the same.
