### ISSUE TITLE
F.Promise with Multi Object to Scala Template Play Framework Java

### ISSUE THREAD

**Issue by sivailango** [ReactiveCouchbase/ReactiveCouchbase-play#44]
I have two objects bookmark, bookmarks, i want to pass object as parameters to Scala Templates like

return ok(views.html.bookmarks.list.render(bookmark, bookmarks));

in F.Promise,

    F.Promise<Bookmark> bookmark = Bookmark.findById(id);
    F.Promise<Collection<Bookmark>> bookmarks = Bookmark.findAll();
    // here how to write the code that should pass both objects to scala template
}

How to write the return statement to pass these two objects in F.Promise without Json Result?

**Comment by mathieuancelin** [comment]
Hi,

Promise design is really made to promote composition. So you can compose any Promise with other Promises using `flatMap` and `map`. If you have a lot of promises to compose, it can be pretty tedious to write, but it's doable, especially if you're using Java 8. If you're using Scala, you can easily replace all `map` and `flatMap` calls with a single for comprehension expression.

Anyway, in Java you just have to write something like : 

```java
public class BookmarkController extends Controller {

    public static F.Promise<Result> list(Long id) {
        F.Promise<Bookmark> futureBookmark = Bookmark.findById(id);
        F.Promise<Collection<Bookmark>> futureBookmarks = Bookmark.findAll();
        return futureBookmark.flatMap(bookmark ->
            futureBookmarks.map(bookmarks ->
                ok(views.html.bookmarks.list.render(bookmark, bookmarks))
            )
        );
    }
}
```

**Comment by sivailango** [comment]
I tried with your code,

public static F.Promise<Result> get(String id) {
		F.Promise<Bookmark> futureBookmark = Bookmark.findById(id);
        F.Promise<Collection<Bookmark>> futureBookmarks = Bookmark.findAll();
        return futureBookmark.flatMap(futureBookmark ->
        	futureBookmarks.map(futureBookmarks ->
        		ok(views.html.bookmarks.list.render(futureBookmark, futureBookmarks))
        	)
        );
}

But it shows warning at return futureBookmark.flatMap(futureBookmark -> and futureBookmarks.map(futureBookmarks ->,  futureBookmark wants to cast into int, futureBookmarks wants to cast into Status ,also may i know, where the bookmark, bookmarks came from in your code return statement? since you have used futureBookmark, futureBookmarks.

**Comment by mathieuancelin** [comment]
it seems the name of the closures args are the same than promises

```java
futureBookmark.flatMap(futureBookmark ->
```

should be

```java
futureBookmark.flatMap(bookmark ->
```

and the same for `futureBookmarks`

**Comment by sivailango** [comment]
<pre lang="java">
public static F.Promise<Result> get(final String id) {
		F.Promise<Bookmark> futureBookmark = Bookmark.findById(id);
        F.Promise<Collection<Bookmark>> futureBookmarks = Bookmark.findAll();
        return futureBookmark.flatMap(bookmark -> 
        	futureBookmarks.map(bookmarks ->
                ok(views.html.bookmarks.render(bookmark, bookmarks))
            )
        );
	}
</pre>

I am getting the 

Multiple markers at this line
	- bookmark cannot be resolved to a variable
	- Syntax error on token "-", -- expected
	- Line breakpoint:Bookmarks [line: 30] - 
	 get(String)

error on eclipse.

**Comment by mathieuancelin** [comment]
I guess you're not using Java 8

**Comment by sivailango** [comment]
Yes... Just i was thinking, it is Java 8 code. Is it possible to achieve in Java 7?

**Comment by mathieuancelin** [comment]
Yes you can write it like : 

```java
    public static F.Promise<Result> index(Long id) {
        F.Promise<Bookmark> futureBookmark = Bookmark.findById(id);
        F.Promise<Collection<Bookmark>> futureBookmarks = Bookmark.findAll();
        return futureBookmark.flatMap(new F.Function<Bookmark, F.Promise<Result>>() {
            @Override
            public F.Promise<Result> apply(final Bookmark bookmark) throws Throwable {
                return futureBookmarks.map(new F.Function<Collection<Bookmark>, Result>() {
                    @Override
                    public Result apply(Collection<Bookmark> bookmarks) throws Throwable {
                        return ok(views.html.bookmarks.list.render(bookmark, bookmarks));
                    }
                });
            }
        });
    }
```

**Comment by sivailango** [comment]
Thanks @mathieuancelin. Now its working, Are there any sites to learn the functional programming in Java 7?

**Comment by mathieuancelin** [comment]
I have no idea. Several libraries provide that kind of paradigm.

Actually it's very similar to Java 8 closures. You just have to write de full code for the anonymous inner classes. You IDE should provide all the support you need to know what to write
